apiVersion: v2
name: gpu-operator
version: 1.3.0
kubeVersion: ">= 1.13.0-0"
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
appVersion: "1.3.0"
icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
sources:
- https://github.com/NVIDIA/gpu-operator
home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
keywords:
  - gpu
  - cuda
  - compute
  - operator
  - deep learning
  - monitoring
  - tesla

dependencies:
  - name: node-feature-discovery
    version: 2.0.0
    repository: "https://k8s-at-home.com/charts/"
    condition: nfd.enabled
