# Default values for gpu-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

platform:
  openshift: false

nfd:
  enabled: true

operator:
  repository: nvidia
  image: gpu-operator
  version: latest
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  defaultRuntime: docker
  deployGFD: true
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"
  annotations:
    openshift.io/scc: restricted-readonly
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]
  logging:
    timeEncoding: epoch

driver:
  repository: nvcr.io/nvidia
  image: driver
  version: "450.80.02"
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    nvidia.com/gpu.present: "true"
  affinity: {}
  podSecurityContext: {}
  securityContext:
    privileged: true
    seLinuxOptions:
      level: "s0"
  resources: {}

toolkit:
  repository: nvcr.io/nvidia/k8s
  image: container-toolkit
  version: 1.3.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  tolerations:
  # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
  # This, along with the annotation above marks this pod as a critical add-on.
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    nvidia.com/gpu.present: "true"
  affinity: {}
  podSecurityContext: {}
  securityContext:
    privileged: true
    seLinuxOptions:
      level: "s0"
  resources: {}

devicePlugin:
  repository: nvcr.io/nvidia
  image: k8s-device-plugin
  version: v0.7.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  tolerations: []
  nodeSelector:
    nvidia.com/gpu.present: "true"
  affinity: {}
  podSecurityContext: {}
  securityContext:
    privileged: true
  resources: {}

dcgmExporter:
  repository: nvcr.io/nvidia/k8s
  image: dcgm-exporter
  version: 2.0.10-2.1.0-rc.2-ubuntu20.04
  imagePullPolicy: IfNotPresent
  tolerations: []
  nodeSelector: {}
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}

gfd:
  repository: nvidia
  image: gpu-feature-discovery
  version: v0.2.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  tolerations: []
  nodeSelector:
    nvidia.com/gpu.present: "true"
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  migStrategy: none
  discoveryIntervalSeconds: 60

node-feature-discovery:
  worker:
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"

    options:
      sources:
        pci:
          deviceLabelFields:
          - vendor
