include:
  - local: '.common-ci.yml'
  - project: nvidia/container-infrastructure/aws-kube-ci
    file: aws-kube-ci.yml
    ref: 21.06.24

.e2e_defaults:
  variables:
    VERSION: "${CI_COMMIT_SHA}-ubi8"
    TF_VAR_project_name: "gpu-operator"
    TF_VAR_additional_ingress_ip_ranges: '["216.228.112.0/26", "217.111.27.192/26"]'
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-end-to-end-tests/
      - $SKIP_TESTS =~ /^y/
      - $CI_PIPELINE_SOURCE == "schedule"

.e2e_tests:
  extends:
    - .e2e_defaults
  stage: e2e_tests
  image: alpine
  variables:
    SKIP_LAUNCH: "true"
  before_script:
    - apk add --no-cache openssh-client rsync bash
  script:
    - source aws-kube-ci/hostname
    - export private_key="${CI_PROJECT_DIR}/aws-kube-ci/${private_key}"
    - export instance_hostname="${instance_hostname}"
    - rc=0
    - ${CI_PROJECT_DIR}/tests/ci-run-e2e.sh ${CI_REGISTRY_IMAGE} ${VERSION} || rc=$?
    - ${CI_PROJECT_DIR}/tests/scripts/pull.sh /tmp/logs logs
    - exit $rc
  artifacts:
    when: always
    paths:
      - logs/

e2e_tests_containerd:
  extends:
    - .e2e_tests
  dependencies:
    - aws_kube_setup_containerd
  needs:
    - aws_kube_setup_containerd
  variables:
    CONTAINER_RUNTIME: "containerd"

e2e_tests_docker:
  extends:
    - .e2e_tests
  dependencies:
    - aws_kube_setup_docker
  needs:
    - aws_kube_setup_docker
  variables:
    CONTAINER_RUNTIME: "docker"

e2e_tests_legacy:
  extends:
    - .e2e_tests
  dependencies:
    - aws_kube_setup_legacy
  needs:
    - aws_kube_setup_legacy

.launch_infra:
  extends:
    - .aws_kube_setup
    - .e2e_defaults
  variables:
    TF_VAR_project_name: "gpu-operator"
    TF_VAR_additional_ingress_ip_ranges: '["216.228.112.0/26", "217.111.27.192/26"]'

aws_kube_setup_containerd:
  extends:
    - .launch_infra
  variables:
    TF_VAR_legacy_setup: "false"
    TF_VAR_container_runtime: "containerd"
    TF_VAR_project_name: "gpu-operator-containerd"

aws_kube_setup_docker:
  extends:
    - .launch_infra
  variables:
    TF_VAR_legacy_setup: "false"
    TF_VAR_container_runtime: "docker"
    TF_VAR_project_name: "gpu-operator-docker"

aws_kube_setup_legacy:
  extends:
    - .launch_infra

aws_kube_clean_containerd:
  extends:
    - .aws_kube_clean
    - .e2e_defaults
  variables:
    TF_VAR_legacy_setup: "false"
    TF_VAR_container_runtime: "containerd"
    TF_VAR_project_name: "gpu-operator-containerd"
  dependencies:
    - aws_kube_setup_containerd

aws_kube_clean_docker:
  extends:
    - .aws_kube_clean
    - .e2e_defaults
  variables:
    TF_VAR_legacy_setup: "false"
    TF_VAR_container_runtime: "docker"
    TF_VAR_project_name: "gpu-operator-docker"
  dependencies:
    - aws_kube_setup_docker

aws_kube_clean_legacy:
  extends:
    - .aws_kube_clean
    - .e2e_defaults
  dependencies:
    - aws_kube_setup_legacy
