apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: gpu-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-operator
  namespace: system
  labels:
    control-plane: gpu-operator
spec:
  selector:
    matchLabels:
      control-plane: gpu-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: gpu-operator
    spec:
      securityContext:
        runAsUser: 65532
      containers:
      - command:
        - gpu-operator
        args:
        - --leader-elect
        image: nvidia/gpu-operator:latest
        name: gpu-operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 50Mi
        volumeMounts:
          - name: host-os-release
            mountPath: "/host-etc/os-release"
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: host-os-release
          hostPath:
            path: "/etc/os-release"
