---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-operator
  labels:
    app.kubernetes.io/component: gpu-operator
    name: gpu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: gpu-operator
      name: gpu-operator
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: gpu-operator
        name: gpu-operator
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: gpu-operator
      containers:
      - name: gpu-operator
        image: nvcr.io/nvidia/gpu-operator:1.7.0
        args:
          - --leader-elect
        command:
          - gpu-operator
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - mountPath: /host-etc/os-release
            name: host-os-release
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - hostPath:
            path: /etc/os-release
          name: host-os-release
