apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-mig-manager
  namespace: gpu-operator-resources
  labels:
    app: nvidia-mig-manager
spec:
  selector:
    matchLabels:
      app: nvidia-mig-manager
  template:
    metadata:
      labels:
        app: nvidia-mig-manager
    spec:
      serviceAccount: nvidia-mig-manager
      containers:
      - name: nvidia-mig-manager
        image: "FILLED_BY_OPERATOR"
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CONFIG_FILE
          value: "/mig-parted-config/config.yaml"
        - name: WITH_REBOOT
          value: "FILLED_BY_OPERATOR"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys
          name: host-sys
        - mountPath: /mig-parted-config
          name: mig-parted-config
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
          type: Directory
      - name: mig-parted-config
        configMap:
          name: mig-parted-config