apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-dcgm-exporter
  namespace: gpu-operator-resources
  labels:
    app: nvidia-dcgm-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-dcgm-exporter
subjects:
- kind: ServiceAccount
  name: nvidia-dcgm-exporter
  namespace: gpu-operator-resources
userNames:
- system:serviceaccount:gpu-operator-resources:nvidia-dcgm-exporter
