apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  operator:
    defaultRuntime: docker
    deployGFD: true
  driver:
    repository: nvcr.io/nvidia
    image: driver
    version: "450.80.02"
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  toolkit:
    repository: nvcr.io/nvidia/k8s
    version: 1.3.0
    image: container-toolkit
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  devicePlugin:
    repository: nvcr.io/nvidia
    image: k8s-device-plugin
    version: v0.7.0
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  dcgmExporter:
    repository: nvcr.io/nvidia/k8s
    image: dcgm-exporter
    version: 2.0.10-2.1.0-rc.2-ubuntu20.04
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
  gfd:
    repository: nvidia
    image: gpu-feature-discovery
    version: v0.2.0
    tolerations: []
    nodeSelector: {}
    affinity: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    migStrategy: none
    discoveryIntervalSeconds: 60
