apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  operator:
    defaultRuntime: crio
    runtimeClass: nvidia
    initContainer: {}

  psp:
    enabled: false

  mig:
    strategy: single

  daemonsets: {}

  validator:
    plugin:
    env:
      - name: WITH_WORKLOAD
        value: "true"

  devicePlugin: {}

  gfd: {}

  toolkit:
    enabled: true

  dcgm:
    enabled: true

  dcgmExporter:
    # configmap name for custom dcgm metrics
    config:
      name: ""

  migManager:
    enabled: true
    config:
      name: ""

  nodeStatusExporter:
    enabled: false
  
  driver:
    enabled: true
    rdma:
      enabled: false
    # private mirror repository configuration
    repoConfig:
      configMapName: ""
    # custom ssl key/certificate configuration
    certConfig:
      name: ""
    # vGPU licensing configuration
    licensingConfig:
      configMapName: ""
      nlsEnabled: false
    # vGPU topology daemon configuration
    virtualTopology:
      config: ""
