apiVersion: v1
kind: Service
metadata:
  namespace: gpu-operator-resources
  name: nvidia-node-status-exporter
  labels:
    app: nvidia-node-status-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: nvidia-node-status-exporter
  ports:
  - name: node-status
    port: 8000
    targetPort: 8000
    protocol: TCP
