apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sev-snp-rule
spec:
  rules:
  - labels:
      sev.snp.enabled: "true"
    matchFeatures:
    - feature: cpu.security
      matchExpressions:
        sev.snp.enabled:
          op: IsTrue
    name: "SEV-SNP rule"
  - labels:
      sev.es.enabled: "true"
    matchFeatures:
    - feature: cpu.security
      matchExpressions:
        sev.es.enabled:
          op: IsTrue
    name: "SEV-ES rule"
  - extendedResources:
      sev_asids: '@cpu.security.sev.asids'
      sev_es: '@cpu.security.sev.encrypted_state_ids'
    matchFeatures:
    - feature: cpu.security
      matchExpressions:
        sev.enabled:
          op: Exists
    name: SEV system capacitys