apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: tdx-total-keys
spec:
  rules:
  - labels:
      sev.enabled: "true"
    name: "TDX rule"
    matchFeatures:
      - feature: cpu.security
        matchExpressions:
            tdx.enabled: {op: IsTrue}
  - name: "TDX total keys rule"
    extendedResources:
      - tdx.total_keys: "@cpu-security.tdx.total_keys"
    matchFeatures:
      - feature: cpu.security
        matchExpressions:
          tdx.enabled: {op: IsTrue}