apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-device-plugin-validation
  name: nvidia-device-plugin-validation
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  readOnlyRootFilesystem: true
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "nvidia/samples:vectoradd-cuda10.2"
      securityContext:
        allowPrivilegeEscalation: false
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
